# See https://github.com/samueleaton/sentry/blob/master/.sentry.example.yml
# for more information about configuration options.

# By default, this file configures sentry to run the native specs for Myst
# Typecheck every time any of the source files changes.
display_name: typecheck specs
info: true
# `|| echo` makes sure that sentry keeps running even if the specs fail.
build: crystal spec || echo ''
run: echo ''
watch:
  - ./src/**/*.cr
  - ./spec/**/*.cr
