require "spec"
require "../src/typecheck.cr"

# Assert that the type inferred type of the given source code
# matches the given type name. The type name should be the path
# that would be used to refer to that type in the given program.
def it_types(source : String, type_name : String, line=__LINE__, file=__FILE__, end_line=__END_LINE__)
  it "types `#{source}` as `#{type_name}`", line: line, file: file, end_line: end_line do
    env, result = Myst::TypeCheck.typecheck(source)
    result.name.should eq(type_name)
  end
end

def it_types(source : String, *, environment : Hash(String, String), line=__LINE__, file=__FILE__, end_line=__END_LINE__)
  it "types the environment of `#{source}`", line: line, file: file, end_line: end_line do
    env, result = Myst::TypeCheck.typecheck(source)
    environment.each do |name, type|
      env.current_scope[name].name.should eq(type)
    end
  end
end


# Run typechecking on the given source, returning the environment
# generated by the program.
def typecheck(source : String)
  Myst::TypeCheck.typecheck(source)
end
